

variables:
  POSTGRES_HOST: postgreshost
  POSTGRES_PORT: 5432
  POSTGRES_USER: siaftest
  POSTGRES_PASSWORD: siaftest

stages:
  - test
  - qa

py27:
  image: py27
  stage: test
  services:
    - name: postgres:9.6
      alias: postgreshost
  script:
    - apk add --no-cache poppler-utils
    - pip install -r dev-requirements.txt
    - pip install .
    - py.test

flake8:
  image: flake8
  stage: test
  script:
    - flake8

sonarqube:
  image: skilldlabs/sonar-scanner
  stage: qa
  script:
    - tox -e sonar
