sn:
  twitter:
    url: https://twitter.com/FranceArchives
    title: Follow FranceArchives on Twitter

  youtube:
    url: https://www.youtube.com/channel/UChKZFqPD_Xk82UjCQUtLBrg
    title: Follow FranceArchives on Youtube


footer-sections:
  - labels: {fr: 'sites publics', en: 'public websites'}
    links:
      - url: https://www.legifrance.gouv.fr/
        labels: {fr: légifrance}
      - url: http://www.cada.fr/
        labels: {fr: CADA}
      - url: https://www.service-public.fr/
        labels: {fr: 'service-public.fr'}
      - url: http://data.gouv.fr
        labels: {fr: data.gouv.fr}
      - url: https://www.cnil.fr
        labels: {fr: CNIL}

  - labels: {fr: "sites d'archives"}
    links:
      - url: https://www.archivesportaleurope.net/fr/home
        labels: {fr: 'Portail européen des Archives', en: 'Archives Portal Europe'}
      - url: http://siafdroit.hypotheses.org/
        labels: {fr: 'Droit des archives'}
      - url: http://siaf.hypotheses.org/
        labels: {fr: 'Modernisation et archives'}
      - url: http://www.culture.fr/Genealogie/Grand-Memorial
        labels: {fr: 'Grand mémorial'}
      - url: http://www.memoiredeshommes.sga.defense.gouv.fr/
        labels: {fr: 'Mémoire des hommes'}

  - labels: {fr: 'liens utiles', en: 'useful links'}
    links:
      - url: "%(base_url)sservices"
        labels: {fr: 'Annuaire des services', en: 'Service directory'}
      - url: "%(base_url)sarticle/38167"
        labels: {fr: 'Annuaire du SIAF', en: 'SIAF directory'}
      - url: "%(base_url)sannuaire/departements"
        labels: {fr: "Carte des services d'archives"}
        tooltips: {fr: 'Page donnant les références des Sites Web des archives départementales'}
      - url: "%(base_url)scirculaires"
        labels: {fr: 'Circulaires', en: 'Circulars'}
      - url: "%(base_url)sfaq"
        labels: {fr: 'Questions-réponses', en: 'FAQ'}
      - url: "%(base_url)semplois"
        labels: {fr: "Offres d'emploi"}
      - url: "%(base_url)sabout"
        labels: {fr: 'Rejoindre le portail'}
      - url: "%(base_url)sinventaires/"
        labels: {fr: "Tous les documents d'archives"}

footer-links:
  - url: "%(base_url)scontact"
    labels: {fr: contact}
  - url: "%(base_url)sopen_data"
    labels: {fr: 'open data'}
  - url: "%(base_url)ssitemap"
    labels: {fr: 'plan du site'}
  - url: "%(base_url)slegal_notices"
    labels: {fr: 'mentions légales'}
  - url: "%(base_url)sprivacy_policy"
    labels: {fr: 'données personnelles'}
  - url: "%(base_url)saccessibility"
    labels: {fr: accessibilité, en: accessibility}
